"""
Trade Entry Analyzer
====================

This script analyzes a trade log file generated by the system performance backtester
to determine the quality of the AI model's "BUY" signal timing.

It answers the key question: "After the model issues a BUY signal, does the
price tend to dip immediately (offering a better entry), or does it rise?"

Functionality:
1.  Reads a specified trade log CSV file provided via a command-line argument.
2.  For each "BUY" trade, it loads the corresponding historical price data for the correct agent.
3.  It examines the 5 days immediately following the purchase to find the lowest price.
4.  It calculates the drawdown from the entry price to this subsequent low.
5.  It classifies each trade as:
    - 'Dip Buy': If the price dropped more than 1% after the purchase.
    - 'Rising Buy': If the price held steady or rose after the purchase.

Outputs:
- A summary table printed to the console.
- The overall percentage of trades that were "Dip Buys".
- A detailed CSV report saved in the 'reports/backtest_results/' directory,
  named after the agent being analyzed (e.g., 'trade_entry_analysis_dynamic.csv').

Usage:
    python analyze_trades.py --agent <agent_name> --log-file <path_to_log_file.csv>

Example:
    python analyze_trades.py --agent dynamic --log-file "backtest_results/trade_log_dynamic_Backtesting.csv"
"""


# analyze_trades.py (V2 - Flexible with Command-Line Arguments)
import pandas as pd
import os
import argparse
from data_manager import DataManager
from tqdm import tqdm

# A dictionary to map agent names to their data directories
AGENT_DATA_DIRS = {
    "dynamic": "models/NASDAQ-testing set/features/dynamic_profit",
    "2pct": "models/NASDAQ-testing set/features/2per_profit",
    "3pct": "models/NASDAQ-testing set/features/3per_profit",
    "4pct": "models/NASDAQ-testing set/features/4per_profit"
}


def analyze_trade_entries(backtest_log_path: str, data_manager: DataManager):
    """
    Analyzes trade entries to determine if they were 'dip buys' or 'rising buys'.
    """
    print(f"🔎 Analyzing trade log: {backtest_log_path}")
    trades_df = pd.read_csv(backtest_log_path, parse_dates=['entry_date'])

    buy_trades = trades_df[trades_df['action'] == 'BUY'].copy()
    if buy_trades.empty:
        print("No 'BUY' trades found in the log to analyze.")
        return

    results = []
    look_forward_days = 5

    for _, trade in tqdm(buy_trades.iterrows(), total=len(buy_trades), desc="Analyzing Trades"):
        symbol = trade['symbol']
        entry_date = trade['entry_date']
        entry_price = trade['entry_price']

        stock_df = data_manager.load_feature_file(symbol)
        if stock_df is None:
            continue

        trade_window = stock_df[stock_df.index > entry_date].head(look_forward_days)
        if trade_window.empty:
            continue

        lowest_price_after_buy = trade_window['low'].min() # Use lowercase 'low'
        drawdown = (entry_price - lowest_price_after_buy) / entry_price * 100
        trade_type = "Dip Buy" if drawdown > 1.0 else "Rising Buy"

        results.append({
            'symbol': symbol,
            'entry_date': entry_date.date(),
            'entry_price': entry_price,
            'lowest_price_in_5_days': lowest_price_after_buy,
            'max_drawdown_pct': drawdown,
            'trade_type': trade_type
        })

    if not results:
        print("Could not generate any analysis results.")
        return

    analysis_df = pd.DataFrame(results)
    print("\n--- Trade Entry Analysis Summary ---")
    print(analysis_df.round(2))
    dip_buy_pct = (analysis_df['trade_type'] == 'Dip Buy').mean() * 100
    print(f"\n📈 Percentage of trades that were 'Dip Buys': {dip_buy_pct:.2f}%")

    # Ensure the directory exists
    output_dir = os.path.join("reports", "backtest_results")
    os.makedirs(output_dir, exist_ok=True)
    # Save the file with a name that includes the agent
    agent_name = os.path.basename(backtest_log_path).split('_')[2]
    output_path = os.path.join(output_dir, f"trade_entry_analysis_{agent_name}.csv")
    analysis_df.to_csv(output_path, index=False)
    print(f"✅ Full report saved to: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Analyze trade entries from a backtest log.")
    # NEW: Command-line arguments to make the script flexible
    parser.add_argument('--agent', required=True, type=str, choices=list(AGENT_DATA_DIRS.keys()),
                        help='Select which agent to analyze (e.g., "dynamic").')
    parser.add_argument('--log-file', required=True, type=str,
                        help='Path to the specific trade log file to analyze.')
    args = parser.parse_args()

    data_dir = AGENT_DATA_DIRS[args.agent]

    if os.path.exists(args.log_file) and os.path.exists(data_dir):
        dm = DataManager(feature_dir=data_dir)
        analyze_trade_entries(args.log_file, dm)
    else:
        print(f"Error: Make sure the trade log exists at '{args.log_file}' and data exists at '{data_dir}'.")