# decision_logger.py
"""
StockWise Gen-13 — Decision Logger (Observability Layer)
=========================================================
Append-only JSONL audit trail for every signal, veto, risk-gate,
execution and exit decision made by the live trading engine.

Usage:
    from decision_logger import DecisionLogger
    dl = DecisionLogger()
    dl.log_signal("AAPL", "MOMENTUM_BREAKOUT", confidence=87.0, regime="TREND")
    dl.log_veto("AAPL", gate="market_hours", passed=False, reason="Pre-market")
    dl.log_risk("AAPL", gate="correlation", passed=True, reason="OK")
    dl.log_execution("AAPL", action="BUY", price=150.0, qty=10, stop=145.0, target=165.0)
    dl.log_exit("AAPL", exit_price=162.0, pnl_pct=8.0, reason="TAKE_PROFIT")
"""

import json
import logging
import os
import time
from datetime import datetime, timezone

import system_config as cfg

logger = logging.getLogger(__name__)

_DEFAULT_CONFIG = {
    "log_dir": "data/decision_logs",
    "log_filename": "decisions.jsonl",
    "max_log_size_mb": 50,
    "max_rotated_files": 5,
    "log_signal_events": True,
    "log_veto_events": True,
    "log_risk_events": True,
    "log_execution_events": True,
    "log_exit_events": True,
    "async_write": False,
    "flush_every_n_events": 1,
    "schema_version": "1.0",
}


class DecisionLogger:
    """
    Append-only JSONL decision logger for the live trading pipeline.

    Each event is a single JSON object on its own line with:
      - ts        : ISO-8601 UTC timestamp
      - event     : event type string
      - symbol    : ticker symbol
      - schema_v  : schema version from config
      - ... event-specific fields
    """

    def __init__(self):
        self.config = {**_DEFAULT_CONFIG, **getattr(cfg, "OBSERVABILITY_CONFIG", {})}
        self._log_dir = self.config["log_dir"]
        self._log_path = os.path.join(self._log_dir, self.config["log_filename"])
        self._schema_v = self.config["schema_version"]
        self._event_count = 0
        self._file_handle = None

        os.makedirs(self._log_dir, exist_ok=True)
        self._open_file()

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def log_signal(self, symbol: str, template_id: str, confidence: float,
                   regime: str = "", **kwargs) -> None:
        """Log a template signal generated by the scanner."""
        if not self.config.get("log_signal_events", True):
            return
        self._write({
            "event": "SIGNAL",
            "symbol": symbol,
            "template_id": template_id,
            "confidence": confidence,
            "regime": regime,
            **kwargs,
        })

    def log_veto(self, symbol: str, gate: str, passed: bool,
                 reason: str = "", **kwargs) -> None:
        """Log a veto-gate decision (pass or block)."""
        if not self.config.get("log_veto_events", True):
            return
        self._write({
            "event": "VETO",
            "symbol": symbol,
            "gate": gate,
            "passed": passed,
            "reason": reason,
            **kwargs,
        })

    def log_risk(self, symbol: str, gate: str, passed: bool,
                 reason: str = "", **kwargs) -> None:
        """Log a risk-gate decision."""
        if not self.config.get("log_risk_events", True):
            return
        self._write({
            "event": "RISK",
            "symbol": symbol,
            "gate": gate,
            "passed": passed,
            "reason": reason,
            **kwargs,
        })

    def log_execution(self, symbol: str, action: str, price: float,
                      qty: int, stop: float, target: float, **kwargs) -> None:
        """Log a trade execution (execute_ticket call)."""
        if not self.config.get("log_execution_events", True):
            return
        self._write({
            "event": "EXECUTION",
            "symbol": symbol,
            "action": action,
            "price": price,
            "qty": qty,
            "stop": stop,
            "target": target,
            **kwargs,
        })

    def log_exit(self, symbol: str, exit_price: float, pnl_pct: float,
                 reason: str = "", **kwargs) -> None:
        """Log a position exit."""
        if not self.config.get("log_exit_events", True):
            return
        self._write({
            "event": "EXIT",
            "symbol": symbol,
            "exit_price": exit_price,
            "pnl_pct": pnl_pct,
            "reason": reason,
            **kwargs,
        })

    def close(self) -> None:
        """Flush and close the log file."""
        if self._file_handle and not self._file_handle.closed:
            self._file_handle.flush()
            self._file_handle.close()
            self._file_handle = None

    # ─────────────────────────────────────────────────────────────────────────
    # Internal helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _write(self, payload: dict) -> None:
        """Serialize payload to JSONL and flush if needed. Rotates on size limit."""
        record = {
            "ts": datetime.now(timezone.utc).isoformat(),
            "schema_v": self._schema_v,
            **payload,
        }
        line = json.dumps(record, separators=(",", ":")) + "\n"

        try:
            self._rotate_if_needed()
            self._file_handle.write(line)
            self._event_count += 1
            flush_every = self.config.get("flush_every_n_events", 1)
            if flush_every <= 1 or self._event_count % flush_every == 0:
                self._file_handle.flush()
        except Exception as exc:
            logger.warning("DecisionLogger write failed: %s", exc)

    def _open_file(self) -> None:
        """Open (or re-open after rotation) the log file in append mode."""
        try:
            self._file_handle = open(self._log_path, "a", encoding="utf-8")
        except OSError as exc:
            logger.error("DecisionLogger cannot open %s: %s", self._log_path, exc)
            self._file_handle = None

    def _rotate_if_needed(self) -> None:
        """Rotate log file when it exceeds max_log_size_mb."""
        if self._file_handle is None or self._file_handle.closed:
            self._open_file()
            return

        max_bytes = self.config.get("max_log_size_mb", 50) * 1024 * 1024
        try:
            size = os.path.getsize(self._log_path)
        except OSError:
            return

        if size < max_bytes:
            return

        # Close current handle, rotate, re-open
        self._file_handle.flush()
        self._file_handle.close()

        max_keep = self.config.get("max_rotated_files", 5)
        # Shift existing rotated files: .5 → drop, .4 → .5, ..., .1 → .2
        for i in range(max_keep, 0, -1):
            old = f"{self._log_path}.{i}"
            new = f"{self._log_path}.{i + 1}"
            if os.path.exists(old):
                if i >= max_keep:
                    os.remove(old)
                else:
                    os.rename(old, new)
        # Rename current to .1
        if os.path.exists(self._log_path):
            os.rename(self._log_path, f"{self._log_path}.1")

        self._open_file()

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass
