"""
Automated Backtest & Archiving Pipeline
=========================================

This script automates the process of running a full, comprehensive backtest of the
trading system and then archiving the results into a master Excel workbook.

It is designed to be a simple, one-command way to execute a full validation run
and permanently store its performance metrics for later comparison.

Key Functionality:
------------------
1.  **Run Backtest (`run_backtest`):**
    -   Executes the `test_system_performance.py` script using `pytest` in
        'long' mode to ensure a full, comprehensive backtest is performed.
    -   Streams the output of the pytest command directly to the console in
        real-time, allowing the user to see the progress bars and any logs
        as they happen.
    -   Checks the exit code to confirm the backtest completed successfully.

2.  **Archive Results (`archive_results`):**
    -   If the backtest is successful, this function reads the summary CSV
        file generated by the test run (assumed to be at
        `reports/backtest_results/latest_summary.csv`).
    -   It then appends this data as a new sheet to the master Excel file
        located at `reports/Master_Test_Results.xlsx`.
    -   Each new sheet is named with a unique timestamp (e.g., 'Run_2025-10-03_14-46')
        to create a historical archive of all backtest runs.

Usage:
------
    python <name_of_this_script>.py

"""


import subprocess
import pandas as pd
import os
from datetime import datetime

# --- Configuration ---
BACKTEST_SCRIPT = "test_system_performance.py"
MASTER_RESULTS_FILE = os.path.join("reports", "Master_Test_Results.xlsx")
SUMMARY_INPUT_FILE = os.path.join("reports", "backtest_results", "latest_summary.csv")


def run_backtest():
    """Runs the full backtest, streaming its progress directly to the console."""
    print("--- 🚀 Starting Full System Performance Backtest (long mode) ---")

    command = ["pytest", "-s", BACKTEST_SCRIPT, "--mode=long"]

    # --- Stream pytest output in real-time ---
    # Use Popen without redirecting stdout/stderr to see live progress.
    # The output from pytest (including the tqdm progress bars) will now appear in your terminal.
    process = subprocess.Popen(command, text=True, encoding='utf-8')

    # Wait for the process to complete while its output is being streamed.
    process.wait()

    # Add a newline for cleaner separation after pytest finishes
    print("\n" + "=" * 80)

    if process.returncode != 0:
        print("--- ❌ Backtest script failed with an error ---")
        return False

    print("--- ✅ Backtest script completed successfully ---")
    return True


def archive_results(tab_name):
    """Reads the latest summary and appends it to the master Excel file."""
    print(f"--- 🗄️ Archiving results to sheet: {tab_name} ---")

    try:
        summary_df = pd.read_csv(SUMMARY_INPUT_FILE)

        mode = 'a' if os.path.exists(MASTER_RESULTS_FILE) else 'w'
        if_sheet_exists = 'replace' if mode == 'a' else None

        with pd.ExcelWriter(MASTER_RESULTS_FILE, engine='openpyxl', mode=mode,
                            if_sheet_exists=if_sheet_exists) as writer:
            summary_df.to_excel(writer, sheet_name=tab_name, index=False)

        print(f"--- ✅ Results successfully archived in '{MASTER_RESULTS_FILE}' ---")

    except FileNotFoundError:
        print(f"--- ❌ ERROR: Summary file not found at '{SUMMARY_INPUT_FILE}'. Archiving failed. ---")
    except Exception as e:
        print(f"--- ❌ An error occurred during archiving: {e} ---")


if __name__ == "__main__":
    run_timestamp = datetime.now().strftime("Run_%Y-%m-%d_%H-%M")

    if run_backtest():
        archive_results(tab_name=run_timestamp)