# test_create_parquet_NASDAQ_file.py
#
# This script contains unit tests for the data processing pipeline
# in Create_parquet_file_NASDAQ.py to ensure features are correctly
# calculated and the final DataFrame has the correct schema.

import pytest
import pandas as pd
import numpy as np
import os

# --- Import the specific function we are testing from the main script ---
from Create_parquet_file_NASDAQ import add_technical_indicators_and_features, get_dominant_cycle

# --- Test Fixture: Sample Stock Data ---
@pytest.fixture(scope="module")
def sample_stock_data():
    """
    Creates a realistic, moderately-sized sample DataFrame of stock data for testing.
    The data spans over a year to ensure rolling windows are effective.
    """
    dates = pd.to_datetime(pd.date_range(start='2022-01-01', periods=300))
    close_prices = 100 + np.cumsum(np.random.normal(0, 1.5, size=300))
    data = {
        'Open': close_prices - np.random.uniform(0, 1, size=300),
        'High': close_prices + np.random.uniform(0, 1.5, size=300),
        'Low': close_prices - np.random.uniform(0, 1.5, size=300),
        'Close': close_prices,
        'Volume': np.random.randint(1_000_000, 10_000_000, size=300)
    }
    df = pd.DataFrame(data, index=dates)
    df.index.name = 'Datetime'
    df['Datetime'] = df.index
    return df

# --- Comprehensive Test for all expected features ---
def test_all_expected_features_exist(sample_stock_data):
    """
    Test ID: T1.1
    Verifies that the final output DataFrame contains ALL expected features
    and target columns required by the model trainer. This is a critical
    schema validation test.
    """
    # Define the complete list of columns expected in the final DataFrame
    expected_columns = {
        # Core data
        'Open', 'High', 'Low', 'Close', 'Volume', 'Datetime',
        # Gen-2 Features (retained with correct names)
        'Volume_MA_20', 'RSI_14', 'Momentum_5', 'MACD', 'MACD_Signal', 'MACD_Histogram',
        'BB_Position', 'Volatility_20D', 'ATR_14', 'ADX', 'ADX_pos', 'ADX_neg',
        'OBV', 'RSI_28', 'Dominant_Cycle_126D',
        # New Gen-3 Features
        'Z_Score_20', 'BB_Width', 'Correlation_50D_QQQ', 'Smoothed_Close_5D',
        'RSI_14_Smoothed', 'BB_Upper', 'BB_Lower', 'BB_Middle', 'Daily_Return',
        # Gen-3 and Gen-2 Targets/Labels
        'Volatility_Cluster',
        'Target_Entry', 'Target_Profit_Take', 'Target_Cut_Loss', 'Target'
    }

    # Act
    featured_df = add_technical_indicators_and_features(sample_stock_data.copy(), vol_thresholds=(0.015, 0.03))

    # *** Add this print statement for debugging ***
    print("\nColumns generated by the function:", featured_df.columns.tolist())
    print("Columns expected by the test:", sorted(list(expected_columns)))
    # *********************************************

    # Assert
    missing_cols = expected_columns - set(featured_df.columns)
    assert not missing_cols, f"The following critical columns are missing from the DataFrame: {missing_cols}"
    assert not featured_df.empty, "The DataFrame is empty after feature engineering."


# --- Test Cases for New Gen-3 Features (retained from original script for detail) ---

def test_feature_z_score(sample_stock_data):
    """
    Test ID: FE-02
    Tests if the Z-Score feature is added and contains valid numerical data.
    """
    # Act: Run the feature engineering function
    featured_df = add_technical_indicators_and_features(sample_stock_data.copy(), vol_thresholds=(0.015, 0.03))

    # Assert: Check for existence, type, and validity
    assert 'Z_Score_20' in featured_df.columns, "Z_Score_20 column is missing."
    assert pd.api.types.is_numeric_dtype(featured_df['Z_Score_20']), "Z_Score_20 column is not numeric."
    assert not featured_df['Z_Score_20'].isnull().all(), "Z_Score_20 column contains only NaN values."
    assert featured_df['Z_Score_20'].abs().max() < 10, "Z-Score values seem unexpectedly large."

def test_feature_bollinger_band_width(sample_stock_data):
    """
    Test ID: FE-03
    Tests if the Bollinger Band Width feature is added and valid.
    """
    # Act
    featured_df = add_technical_indicators_and_features(sample_stock_data.copy(), vol_thresholds=(0.015, 0.03))

    # Assert
    assert 'BB_Width' in featured_df.columns, "BB_Width column is missing."
    assert pd.api.types.is_numeric_dtype(featured_df['BB_Width']), "BB_Width column is not numeric."
    assert not featured_df['BB_Width'].isnull().all(), "BB_Width column contains only NaN values."
    assert featured_df['BB_Width'].min() >= 0, "Bollinger Band Width should not be negative."

def test_feature_correlation_to_qqq(sample_stock_data):
    """
    Test ID: FE-04
    Tests if the 50-day correlation to QQQ feature is added and valid.
    """
    # Act
    featured_df = add_technical_indicators_and_features(sample_stock_data.copy(), vol_thresholds=(0.015, 0.03))

    # Assert
    assert 'Correlation_50D_QQQ' in featured_df.columns, "Correlation_50D_QQQ column is missing."
    assert pd.api.types.is_numeric_dtype(featured_df['Correlation_50D_QQQ']), "Correlation_50D_QQQ column is not numeric."
    assert not featured_df['Correlation_50D_QQQ'].isnull().all(), "Correlation_50D_QQQ column contains only NaN values."
    assert featured_df['Correlation_50D_QQQ'].min() >= -1.0, "Correlation cannot be less than -1."
    assert featured_df['Correlation_50D_QQQ'].max() <= 1.0, "Correlation cannot be greater than 1."


def test_feature_volatility_cluster(sample_stock_data):
    """
    Test ID: FE-05
    Tests if the Volatility Cluster feature is added and contains correct labels.
    """
    # Act
    featured_df = add_technical_indicators_and_features(sample_stock_data.copy(), vol_thresholds=(0.015, 0.03))

    # Assert
    assert 'Volatility_Cluster' in featured_df.columns, "Volatility_Cluster column is missing."
    assert pd.api.types.is_string_dtype(featured_df['Volatility_Cluster']), "Volatility_Cluster column should be a string/object type."
    assert not featured_df['Volatility_Cluster'].isnull().all(), "Volatility_Cluster column contains only NaN values."
    valid_clusters = {'low', 'mid', 'high'}
    assert set(featured_df['Volatility_Cluster'].unique()).issubset(valid_clusters), "Volatility_Cluster contains invalid labels."

# --- Placeholder Test for Triple Barrier Labeling ---

def test_triple_barrier_labeling(sample_stock_data):
    """
    Test ID: TL-01
    Tests for the existence and basic integrity of the three new target columns.
    """
    # Act
    featured_df = add_technical_indicators_and_features(sample_stock_data.copy(), vol_thresholds=(0.015, 0.03))

    # Assert: Check for existence
    assert 'Target_Entry' in featured_df.columns, "Target_Entry column is missing."
    assert 'Target_Profit_Take' in featured_df.columns, "Target_Profit column is missing."
    assert 'Target_Cut_Loss' in featured_df.columns, "Target_Cut column is missing."

    # Assert: Check for binary values (0 or 1)
    assert set(featured_df['Target_Entry'].unique()).issubset({0, 1}), "Target_Entry should only contain 0s and 1s."
    assert set(featured_df['Target_Profit_Take'].unique()).issubset({0, 1}), "Target_Profit should only contain 0s and 1s."
    assert set(featured_df['Target_Cut_Loss'].unique()).issubset({0, 1}), "Target_Cut should only contain 0s and 1s."