"""
🔬 Unit Test Script for ProfessionalStockAdvisor

This script runs the self-tests defined within the ProfessionalStockAdvisor class
in stockwise_simulation.py to verify core functionalities.
"""

import os
import sys
import logging
from datetime import datetime, timedelta

# Add the parent directory of stockwise_simulation.py to the Python path
# This assumes stockwise_simulation.py is in the same directory as this test script
# or a directory accessible via typical Python module paths.
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.append(current_dir)

try:
    from stockwise_simulation import ProfessionalStockAdvisor

    print("✅ Successfully imported ProfessionalStockAdvisor.")
except ImportError as e:
    print(f"❌ Error importing ProfessionalStockAdvisor: {e}")
    print("Please ensure 'stockwise_simulation.py' is in the same directory "
          "as 'run_unit_tests.py' or in your Python path.")
    sys.exit(1)

# --- Configuration for Tests ---
# Ensure necessary directories exist for logging and models
LOG_DIR = "logs"
MODELS_DIR = "models/NASDAQ-training set"
os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(MODELS_DIR, exist_ok=True)

# Configure logging for the test script
# This will capture the logs generated by ProfessionalStockAdvisor
log_file_path = os.path.join(LOG_DIR, f"unit_test_log_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log")
logging.basicConfig(
    level=logging.DEBUG,  # Set to DEBUG to capture all messages
    format='%(asctime)s | %(levelname)s | %(message)s',
    handlers=[
        logging.FileHandler(log_file_path, encoding='utf-8'),
        logging.StreamHandler(sys.stdout)  # Also print to console
    ]
)
logging.getLogger('yfinance').setLevel(logging.WARNING)  # Suppress yfinance noise


def main():
    """
    Main function to initialize the advisor and run self-tests.
    """
    logging.info("--- Starting ProfessionalStockAdvisor Unit Tests ---")
    try:
        # Initialize the advisor in debug mode to get verbose output during tests
        # Set use_ibkr=False for unit testing to avoid requiring an IBKR connection
        advisor = ProfessionalStockAdvisor(
            debug=True,
            use_ibkr=False,
            model_dir=MODELS_DIR,
            download_log=True  # Ensure logging to file is active
        )

        logging.info(f"Advisor initialized. Log file for this run: {advisor.log_file}")

        # Run the self-tests
        test_success = advisor.run_self_tests()

        if test_success:
            logging.info("--- All unit tests passed! 🎉 ---")
        else:
            logging.error("--- Some unit tests failed. Check the log file for details. ❌ ---")

    except Exception as e:
        logging.critical(f"An unexpected error occurred during unit tests: {e}")
        logging.critical(f"Traceback:\n{sys.exc_info()[2]}")  # Log full traceback
        sys.exit(1)


if __name__ == "__main__":
    main()
